### PR TITLE
add username and password auth method

### PR DESCRIPTION
**Pull request by PatrickKoss**
Hey :)

I like this project and used it happily in the past. Now I have to use a secrets manager (vault) that currently only support username and password auth. Therefore I think it will be useful (at least for me) to add the userpass auth method.

Best regards,
Patrick

### CODE REVIEW

**Comment by ricoberger** [comment]
Hi @PatrickKoss thanks for your contribution 🙂.

Does it make sense to add a new test in https://github.com/ricoberger/vault-secrets-operator/tree/main/hack similar to the other authentication methods?

**Comment by PatrickKoss** [comment]
Yes @ricoberger it of course makes sense. I was just not aware of the tests :D Added one for username and password. Can you have a look again?

**Comment by ricoberger** [comment]
Awesome work @PatrickKoss and thanks for adding the test.

I think there is only a problem with the file permissions for the added test, which should be fixed by running `chmod +x hack/setup-kind-userpass.sh`, everything else is looking good.

**Comment by PatrickKoss** [comment]
executed the command, so hopefully should work now

**Comment by ricoberger** [comment]
Thank you 🙂

**Pull request merged**
